version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: EST
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: "@glimmer/reference"
    versions:
    - 0.73.2
    - 0.74.0
    - 0.74.2
    - 0.75.0
    - 0.77.1
    - 0.77.3
    - 0.77.6
  - dependency-name: "@glimmer/validator"
    versions:
    - 0.73.2
    - 0.74.0
    - 0.74.2
    - 0.75.0
    - 0.77.1
    - 0.77.3
    - 0.77.6
  - dependency-name: "@glimmer/syntax"
    versions:
    - 0.73.2
    - 0.74.0
    - 0.74.2
    - 0.75.0
    - 0.77.1
    - 0.77.3
    - 0.77.6
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: EST
  open-pull-requests-limit: 10
