language: node_js
node_js:
  - "12"

cache:
  yarn: true

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

stages:
  - test
  - additional tests

jobs:
  include:
    # runs tests with current locked deps and linting
    - stage: test
      name: Tests
      script:
        - yarn lint:js
        - yarn test

    - stage: additional tests
      name: Floating Dependencies
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

    - name: Node 6
      node_js: "6"

    - name: Node 8
      node_js: "8"

    - name: Node 9
      node_js: "9"

    - name: Node 10
      node_js: "10"


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn test
